"""Model Card Generator — generates a model card from training metadata.

Creates a standardized model card document from training outcomes,
checkpoints, and configuration. Useful for sharing trained models
with teams or publishing to HuggingFace.
"""

from __future__ import annotations

import json
import time
from dataclasses import asdict, dataclass, field
from pathlib import Path
from typing import Any, Dict, List, Optional


@dataclass
class ModelCard:
    """A model card for a trained model."""

    # Model info
    model_name: str = ""
    model_type: str = ""
    base_model: str = ""
    description: str = ""

    # Training info
    training_method: str = ""
    dataset: str = ""
    dataset_size: int = 0
    epochs: int = 0
    learning_rate: float = 0.0
    batch_size: int = 0

    # Results
    final_loss: float = 0.0
    perplexity: float = 0.0
    quality_score: float = 0.0
    training_time_s: float = 0.0

    # Metadata
    author: str = ""
    license: str = ""
    tags: List[str] = field(default_factory=list)
    created_at: float = 0.0

    def to_markdown(self) -> str:
        """Generate a markdown model card."""
        lines = [
            f"# {self.model_name or 'Untitled Model'}",
            "",
            "## Overview",
            "",
            self.description or "A fine-tuned model created with SloughGPT.",
            "",
            "## Model Details",
            "",
            f"- **Base Model:** {self.base_model or 'unknown'}",
            f"- **Model Type:** {self.model_type or 'unknown'}",
            f"- **Training Method:** {self.training_method or 'unknown'}",
            f"- **Author:** {self.author or 'SloughGPT'}",
            f"- **License:** {self.license or 'MIT'}",
            "",
            "## Training Data",
            "",
            f"- **Dataset:** {self.dataset or 'unknown'}",
            f"- **Dataset Size:** {self.dataset_size:,} samples" if self.dataset_size else "- **Dataset Size:** unknown",
            f"- **Epochs:** {self.epochs}" if self.epochs else "- **Epochs:** unknown",
            f"- **Learning Rate:** {self.learning_rate}" if self.learning_rate else "- **Learning Rate:** unknown",
            f"- **Batch Size:** {self.batch_size}" if self.batch_size else "- **Batch Size:** unknown",
            "",
            "## Results",
            "",
            f"- **Final Loss:** {self.final_loss:.4f}" if self.final_loss else "- **Final Loss:** N/A",
            f"- **Perplexity:** {self.perplexity:.2f}" if self.perplexity else "- **Perplexity:** N/A",
            f"- **Quality Score:** {self.quality_score:.3f}" if self.quality_score else "- **Quality Score:** N/A",
            f"- **Training Time:** {self.training_time_s:.1f}s" if self.training_time_s else "- **Training Time:** N/A",
            "",
        ]
        if self.tags:
            lines.extend([
                "## Tags",
                "",
                ", ".join(f"`{t}`" for t in self.tags),
                "",
            ])
        lines.extend([
            "---",
            f"*Generated by SloughGPT on {time.strftime('%Y-%m-%d %H:%M:%S', time.localtime(self.created_at or time.time()))}*",
        ])
        return "\n".join(lines)

    def to_dict(self) -> Dict[str, Any]:
        return asdict(self)

    @classmethod
    def from_dict(cls, d: Dict[str, Any]) -> ModelCard:
        return cls(**{k: v for k, v in d.items() if k in cls.__dataclass_fields__})


def generate_model_card(
    name: str,
    base_model: str = "",
    description: str = "",
    dataset: str = "",
    dataset_size: int = 0,
    epochs: int = 0,
    learning_rate: float = 0.0,
    batch_size: int = 0,
    final_loss: float = 0.0,
    perplexity: float = 0.0,
    quality_score: float = 0.0,
    training_time_s: float = 0.0,
    training_method: str = "",
    author: str = "",
    license: str = "",
    tags: Optional[List[str]] = None,
) -> ModelCard:
    """Generate a model card from training parameters."""
    return ModelCard(
        model_name=name,
        base_model=base_model,
        description=description,
        dataset=dataset,
        dataset_size=dataset_size,
        epochs=epochs,
        learning_rate=learning_rate,
        batch_size=batch_size,
        final_loss=final_loss,
        perplexity=perplexity,
        quality_score=quality_score,
        training_time_s=training_time_s,
        training_method=training_method,
        author=author,
        license=license,
        tags=tags or [],
        created_at=time.time(),
    )


def generate_model_card_from_outcome(outcome: Any) -> ModelCard:
    """Generate a model card from a TrainingOutcome."""
    return ModelCard(
        model_name=f"{outcome.model}_{outcome.run_id}",
        base_model=outcome.model,
        description=f"Fine-tuned from {outcome.model} using {outcome.method}",
        dataset=outcome.dataset,
        dataset_size=outcome.dataset_size,
        epochs=outcome.epochs,
        learning_rate=outcome.learning_rate,
        batch_size=outcome.batch_size,
        final_loss=outcome.final_loss,
        perplexity=outcome.perplexity,
        quality_score=outcome.quality_score,
        training_time_s=outcome.training_time_s,
        training_method=outcome.method,
        tags=[outcome.method, outcome.model],
        created_at=outcome.timestamp or time.time(),
    )


__all__ = [
    "ModelCard",
    "generate_model_card",
    "generate_model_card_from_outcome",
]
