"""Backward-compatibility shim — imports from the new ``domain.logging`` package."""

from domain.logging import (
    LogLevel,
    LogRecord,
    Logger,
    ChildLogger,
    TaggedLogger,
    CompositeLogger,
    ErrorCode,
    LogTag,
    ConsoleLogger,
    CLILogger,
    ShellLogger,
    WebLogger,
    WebEventLogger,
    BridgeHandler,
    setup_logging,
    get_request_id,
    set_request_id,
    get_log_context,
    set_log_context,
    clear_log_context,
    get_logger,
    set_global,
    get_global,
)

__all__ = [
    "LogLevel",
    "LogRecord",
    "Logger",
    "ChildLogger",
    "TaggedLogger",
    "CompositeLogger",
    "ErrorCode",
    "LogTag",
    "ConsoleLogger",
    "CLILogger",
    "ShellLogger",
    "WebLogger",
    "WebEventLogger",
    "BridgeHandler",
    "setup_logging",
    "get_request_id",
    "set_request_id",
    "get_log_context",
    "set_log_context",
    "clear_log_context",
    "get_logger",
    "set_global",
    "get_global",
]
