"""Training Domain.

This domain provides unified training capabilities.
All consumers should import from specific submodules:

    from domains.training.service import ...
    from domains.training.checkpoints import ...
    from domains.training.turbo import ...
    from domains.training.data_import import ...
    from domains.training.export import ...
"""

from __future__ import annotations
