"""Backward-compatibility shim — imports from the new ``domain.training`` package."""

from domain.training import (
    DatasetType,
    DataFormat,
    DatasetConfig,
    DatasetManager,
    detect_dataset_type,
    PreprocessingStepType,
    PipelineStageType,
    PipelineConfig,
    TrainingPipeline,
    ModelType,
    ModelArchitecture,
    ModelConfig,
    ModelManager,
    DataPreprocessor,
    find_checkpoint,
    load_soul,
    load_lora_soul,
    LoRAType,
    LoRAConfig,
    LoRALinear,
    LoRAEmbedding,
    apply_lora_to_model,
    get_lora_parameters,
)

__all__ = [
    "DatasetType",
    "DataFormat",
    "DatasetConfig",
    "DatasetManager",
    "detect_dataset_type",
    "PreprocessingStepType",
    "PipelineStageType",
    "PipelineConfig",
    "TrainingPipeline",
    "ModelType",
    "ModelArchitecture",
    "ModelConfig",
    "ModelManager",
    "DataPreprocessor",
    "find_checkpoint",
    "load_soul",
    "load_lora_soul",
    "LoRAType",
    "LoRAConfig",
    "LoRALinear",
    "LoRAEmbedding",
    "apply_lora_to_model",
    "get_lora_parameters",
]
