"""Generated TS contract bindings — the `ts-rs` half of the projection (card 25ebfc0f).

NymVPN annotates its Rust types and lets `cargo test` emit `src/types/tauri.ts`,
so a contract change that isn't regenerated fails at *build* time instead of in
front of a user. `scripts/gen_ts_contracts.py` is our equivalent: one descriptor
(`ToolSpec`) -> HTTP route (`create_router`) -> typed TS
(`apps/web/lib/protocol/contracts.gen.ts`).

Two properties are asserted here:

1. **Freshness** — the committed `contracts.gen.ts` matches what the registry
   produces right now. Runs in a *subprocess* on purpose: `create_router` writes
   to the process-global `_CONTRACTS` registry as a side effect of projection,
   so other tests in the same session (e.g. `test_contract_projection.py`, which
   projects 14 ad-hoc doctor specs) leave rows behind that the committed file
   never contained. In-process comparison would be order-dependent; a fresh
   interpreter reads exactly what boot would.
2. **Completeness** — every registry row carries the fields the frontend
   `ContractDescriptor` type requires (`operation_id`, `module`), so the
   generated file type-checks rather than merely parsing.
"""

from __future__ import annotations

import os
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
SCRIPT = ROOT / "scripts" / "gen_ts_contracts.py"
GENERATED = ROOT / "apps" / "web" / "lib" / "protocol" / "contracts.gen.ts"

# The interpreter roots gen_ts_contracts.py needs to import `routers.*` and
# everything those modules pull in. Mirrors the invocation in the script's
# own docstring.
_PYTHONPATH = [
    ROOT,
    ROOT / "packages" / "mogdb" / "src",
    ROOT / "packages" / "downcraft",
    ROOT / "packages" / "core-py",
    ROOT / "apps" / "api" / "server",
]


def _env() -> dict[str, str]:
    env = dict(os.environ)
    env["PYTHONPATH"] = os.pathsep.join(str(p) for p in _PYTHONPATH)
    # AGENTS.md: a stray `tests` package in ~/.local shadows the repo's tests/.
    env["PYTHONNOUSERSITE"] = "1"
    return env


def test_ts_contract_projection_is_fresh():
    """The committed contracts.gen.ts matches the live descriptor registry."""
    assert SCRIPT.is_file(), f"missing generator: {SCRIPT}"
    assert GENERATED.is_file(), (
        f"missing {GENERATED.relative_to(ROOT)} — run python scripts/gen_ts_contracts.py"
    )

    proc = subprocess.run(
        [sys.executable, str(SCRIPT), "--check"],
        cwd=ROOT,
        env=_env(),
        capture_output=True,
        text=True,
        timeout=300,
        check=False,
    )
    assert proc.returncode == 0, (
        f"contract bindings are stale or the generator failed\n"
        f"stdout: {proc.stdout}\n"
        f"stderr: {proc.stderr}"
    )


def test_registry_rows_carry_frontend_descriptor_fields():
    """Every projected row satisfies the frontend's ContractDescriptor shape.

    `operation_id` and `module` are what let the web client key a read and say
    which router declared the capability; without them `contracts.gen.ts` fails
    `satisfies Record<string, ContractDescriptor>` at typecheck.
    """
    # Importing the pilot registers its own contract as a projection side effect.
    from infrastructure.contract import get_contracts
    from routers.contracts import router  # noqa: F401  (import registers)

    rows = get_contracts()
    assert rows, "no projected contracts registered — create_router did not run"

    for row in rows:
        name = row["name"]
        assert row.get("operation_id"), f"{name} has no operation_id"
        assert row.get("module"), f"{name} has no module"
        for field in ("method", "path", "version", "auth_scope", "idempotent", "params"):
            assert field in row, f"{name} missing descriptor field {field!r}"


def test_operation_ids_are_unique_across_crossings():
    """Two crossings may not claim one operation_id — OpenAPI keys on it."""
    from infrastructure.contract import get_contracts

    rows = get_contracts()
    ids = [row["operation_id"] for row in rows]
    assert len(ids) == len(set(ids)), f"duplicate operation_id: {sorted(ids)}"


def test_generated_file_is_marked_generated():
    """The header warns off hand-edits — the file is an artifact, not source."""
    text = GENERATED.read_text(encoding="utf-8")
    assert "GENERATED by scripts/gen_ts_contracts.py" in text
    assert "do not edit by hand" in text
    assert "import type { ContractDescriptor } from './types'" in text
