"""Backward-compatibility shim — imports from the new ``domain.voice`` package."""

from domain.voice import (
    TranscriptionResult,
    SpeechRecognizer,
    BrowserSpeechRecognizer,
    ServerSpeechRecognizer,
    get_speech_recognizer,
    FilterMode,
    AudioFilterConfig,
    FilterResult,
    apply_noise_gate,
    apply_agc,
    normalize_loudness,
    detect_voice_activity,
    apply_audio_filter,
    PhonemeEncoder,
    NUM_PHONEMES,
    text_to_phonemes,
    UnifiedPhonemeEncoder,
    detect_language,
    parse_ssml,
    SpectrogramDecoder,
    GriffinLimVocoder,
    TTSEngine,
)

__all__ = [
    "TranscriptionResult",
    "SpeechRecognizer",
    "BrowserSpeechRecognizer",
    "ServerSpeechRecognizer",
    "get_speech_recognizer",
    "FilterMode",
    "AudioFilterConfig",
    "FilterResult",
    "apply_noise_gate",
    "apply_agc",
    "normalize_loudness",
    "detect_voice_activity",
    "apply_audio_filter",
    "PhonemeEncoder",
    "NUM_PHONEMES",
    "text_to_phonemes",
    "UnifiedPhonemeEncoder",
    "detect_language",
    "parse_ssml",
    "SpectrogramDecoder",
    "GriffinLimVocoder",
    "TTSEngine",
]
