"""
Tests for domains.shared: feature_flags, utils, test_framework.
"""
import json
import time

import pytest

from domains.shared.feature_flags import (
    FeatureFlag,
    FeatureFlags,
    FlagStatus,
    is_enabled,
)
from domains.shared.test_framework import (
    BenchmarkRunner,
    TestFramework,
    TestResult,
    TestSuite,
    mark_test,
)
from domains.shared.utils import (
    Cache,
    RateLimiter,
    Timer,
    clamp,
    find_available_port,
    format_size,
    format_time,
    generate_id,
    get_timestamp,
    hash_string,
    load_json,
    merge_dicts,
    retry,
    save_json,
    validate_config,
)


# ── feature_flags: FeatureFlag ───────────────────────────────────────────

def test_flag_env_var_autogenerated():
    flag = FeatureFlag(name="my_feature", description="d")
    assert flag.env_var == "SLO_FF_MY_FEATURE"


def test_flag_env_var_explicit():
    flag = FeatureFlag(name="my_feature", description="d", env_var="CUSTOM_VAR")
    assert flag.env_var == "CUSTOM_VAR"


def test_flag_disabled_by_default():
    flag = FeatureFlag(name="f", description="d")
    assert flag.is_enabled is False


def test_flag_enabled_status():
    flag = FeatureFlag(name="f", description="d", status=FlagStatus.ENABLED)
    assert flag.is_enabled is True


def test_flag_experimental_counts_as_enabled():
    flag = FeatureFlag(name="f", description="d", status=FlagStatus.EXPERIMENTAL)
    assert flag.is_enabled is True


@pytest.mark.parametrize("value,expected", [("1", True), ("true", True), ("YES", True), ("on", True), ("0", False), ("false", False), ("no", False), ("off", False)])
def test_flag_env_override(monkeypatch, value, expected):
    flag = FeatureFlag(name="f", description="d", status=FlagStatus.DISABLED)
    monkeypatch.setenv("SLO_FF_F", value)
    assert flag.is_enabled is expected


def test_flag_env_override_beats_enabled_status(monkeypatch):
    flag = FeatureFlag(name="f", description="d", status=FlagStatus.ENABLED)
    monkeypatch.setenv("SLO_FF_F", "0")
    assert flag.is_enabled is False


# ── feature_flags: registry ──────────────────────────────────────────────

@pytest.fixture(autouse=True)
def _clean_flags():
    """Snapshot and restore the global flag registry around each test."""
    saved = dict(FeatureFlags._flags)
    saved_status = {k: v.status for k, v in saved.items()}
    yield
    for k, v in saved_status.items():
        FeatureFlags._flags[k].status = v


def test_register_new_flag():
    flag = FeatureFlags.register("test_register_new", description="hello")
    assert flag.name == "test_register_new"
    assert flag in FeatureFlags._flags.values()


def test_register_existing_is_idempotent():
    first = FeatureFlags.register("test_idempotent", description="a")
    second = FeatureFlags.register("test_idempotent", description="b")
    assert first is second


def test_is_enabled_unknown_flag_warns_and_disabled(caplog):
    assert FeatureFlags.is_enabled("no_such_flag") is False
    assert any("Unknown feature flag" in r.message for r in caplog.records)


def test_set_status_updates_flag():
    FeatureFlags.register("test_set_status")
    FeatureFlags.set_status("test_set_status", FlagStatus.ENABLED)
    assert FeatureFlags.is_enabled("test_set_status") is True


def test_set_status_unknown_raises():
    with pytest.raises(KeyError):
        FeatureFlags.set_status("test_missing_status", FlagStatus.ENABLED)


def test_list_all_shape():
    FeatureFlags.register("test_list_all", description="d")
    listing = FeatureFlags.list_all()
    assert "test_list_all" in listing
    item = listing["test_list_all"]
    assert set(item) == {"description", "status", "enabled", "env_var"}
    assert item["env_var"] == "SLO_FF_TEST_LIST_ALL"


def test_defaults_registered():
    assert "slonet_provider" in FeatureFlags._flags
    assert "kv_cache" in FeatureFlags._flags
    assert FeatureFlags.is_enabled("slonet_provider") is True


def test_load_config_nonexistent_keeps_defaults(tmp_path):
    FeatureFlags.load_config(tmp_path / "missing.json")
    assert FeatureFlags._config_path == tmp_path / "missing.json"
    assert FeatureFlags.is_enabled("slonet_provider") is True


def test_load_config_updates_statuses(tmp_path):
    FeatureFlags.register("test_load_config", description="d", status=FlagStatus.DISABLED)
    cfg = tmp_path / "flags.json"
    cfg.write_text(json.dumps({"test_load_config": "enabled"}))
    FeatureFlags.load_config(cfg)
    assert FeatureFlags.is_enabled("test_load_config") is True


def test_load_config_invalid_status_ignored(tmp_path):
    FeatureFlags.register("test_invalid_status", description="d", status=FlagStatus.DISABLED)
    cfg = tmp_path / "flags.json"
    cfg.write_text(json.dumps({"test_invalid_status": "bogus"}))
    FeatureFlags.load_config(cfg)
    assert FeatureFlags.is_enabled("test_invalid_status") is False


def test_load_config_corrupt_json_warns(tmp_path, caplog):
    cfg = tmp_path / "flags.json"
    cfg.write_text("{not json")
    FeatureFlags.load_config(cfg)
    assert any("Failed to load feature flags" in r.message for r in caplog.records)


def test_save_config_roundtrip(tmp_path):
    FeatureFlags.register("test_save_config", description="d", status=FlagStatus.ENABLED)
    cfg = tmp_path / "flags.json"
    FeatureFlags.save_config(cfg)
    data = json.loads(cfg.read_text())
    assert data["test_save_config"] == "enabled"


def test_is_enabled_shortcut():
    assert is_enabled("slonet_provider") is True
    assert is_enabled("definitely_missing_flag") is False


# ── utils ────────────────────────────────────────────────────────────────

def test_generate_id_length_and_prefix():
    rid = generate_id()
    assert len(rid) == 8
    prefixed = generate_id("sess_")
    assert prefixed.startswith("sess_")
    assert len(prefixed) == len("sess_") + 8


def test_hash_string_algorithms():
    assert hash_string("hello") == hashlib_sha256("hello")
    assert hash_string("hello", "md5") == hashlib_md5("hello")
    assert hash_string("hello", "sha1") == hashlib_sha1("hello")


def test_hash_string_unknown_returns_input():
    assert hash_string("hello", "bogus") == "hello"


def test_format_size_units():
    assert format_size(512) == "512.0 B"
    assert format_size(1024) == "1.0 KB"
    assert format_size(1024 * 1024) == "1.0 MB"
    assert format_size(1024 ** 3) == "1.0 GB"
    assert format_size(1024 ** 4) == "1.0 TB"


def test_format_time_units():
    assert format_time(5) == "5.0s"
    assert format_time(90) == "1.5m"
    assert format_time(7200) == "2.0h"
    assert format_time(172800) == "2.0d"


def test_load_save_json_roundtrip(tmp_path):
    path = tmp_path / "data.json"
    payload = {"a": [1, 2, 3], "b": None}
    save_json(payload, str(path))
    assert load_json(str(path)) == payload


def test_load_json_missing_raises(tmp_path):
    with pytest.raises(FileNotFoundError):
        load_json(str(tmp_path / "nope.json"))


def test_merge_dicts_later_wins():
    assert merge_dicts({"a": 1, "b": 2}, {"b": 3, "c": 4}) == {"a": 1, "b": 3, "c": 4}


def test_clamp_values():
    assert clamp(5, 0, 10) == 5
    assert clamp(-1, 0, 10) == 0
    assert clamp(11, 0, 10) == 10


def test_retry_success_first_try():
    calls = []

    @retry(max_attempts=3, delay=0)
    def work():
        calls.append(1)
        return "ok"

    assert work() == "ok"
    assert len(calls) == 1


def test_retry_retries_then_succeeds():
    calls = []

    @retry(max_attempts=3, delay=0)
    def work():
        calls.append(1)
        if len(calls) < 3:
            raise ValueError("boom")
        return "recovered"

    assert work() == "recovered"
    assert len(calls) == 3


def test_retry_gives_up():
    calls = []

    @retry(max_attempts=2, delay=0)
    def work():
        calls.append(1)
        raise ValueError("always")

    with pytest.raises(ValueError, match="always"):
        work()
    assert len(calls) == 2


def test_timer_context_manager():
    with Timer() as t:
        time.sleep(0.01)
    assert t.start is not None
    assert t.end is not None
    assert t.elapsed >= 0.01


def test_cache_set_get():
    cache = Cache(max_size=2)
    cache.set("a", 1)
    cache.set("b", 2)
    assert cache.get("a") == 1
    assert cache.get("missing") is None
    assert len(cache) == 2


def test_cache_evicts_oldest():
    cache = Cache(max_size=2)
    cache.set("a", 1)
    cache.set("b", 2)
    cache.set("c", 3)
    assert cache.get("a") is None
    assert cache.get("b") == 2
    assert cache.get("c") == 3


def test_cache_clear():
    cache = Cache()
    cache.set("a", 1)
    cache.clear()
    assert len(cache) == 0
    assert cache.get("a") is None


def test_rate_limiter_allows_under_limit():
    calls = []

    @RateLimiter(max_calls=3, period=10)
    def work():
        calls.append(1)

    work()
    work()
    work()
    assert len(calls) == 3


def test_rate_limiter_blocks_over_limit():
    @RateLimiter(max_calls=2, period=10)
    def work():
        pass

    work()
    work()
    with pytest.raises(Exception, match="Rate limit exceeded"):
        work()


def test_rate_limiter_window_expiry():
    rl = RateLimiter(max_calls=2, period=0.05)
    for _ in range(2):
        rl(lambda: None)()
    time.sleep(0.06)
    rl(lambda: None)()  # window has passed, allowed again


def test_validate_config():
    assert validate_config({"a": 1, "b": 2}, ["a", "b"]) is True
    assert validate_config({"a": 1}, ["a", "b"]) is False


def test_get_timestamp_iso():
    ts = get_timestamp()
    assert "+00:00" in ts or ts.endswith("Z")


def test_find_available_port_binds():
    port = find_available_port(start_port=39000)
    import socket
    sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    sock.bind(("", port))
    sock.close()


def test_find_available_port_skips_occupied():
    import socket
    blocker = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    blocker.bind(("", 0))
    blocker.listen(1)
    blocked_port = blocker.getsockname()[1]
    port = find_available_port(start_port=blocked_port, max_attempts=5)
    assert port != blocked_port
    blocker.close()


def test_find_available_port_none_available():
    import socket
    socks = []
    try:
        for i in range(3):
            s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
            s.bind(("", 0))
            s.listen(1)
            socks.append(s)
        with pytest.raises(RuntimeError):
            find_available_port(start_port=1, max_attempts=0)
    finally:
        for s in socks:
            s.close()


# ── test_framework ───────────────────────────────────────────────────────

def test_testresult_dataclass():
    r = TestResult(name="t", status="passed", execution_time=0.1)
    assert r.name == "t"
    assert r.status == "passed"
    assert r.error_message is None


def test_testframework_runs_passing_tests():
    fw = TestFramework(name="demo")

    def ok_test():
        assert True

    fw.register(ok_test)
    suite = fw.run()
    assert isinstance(suite, TestSuite)
    assert suite.total_tests == 1
    assert suite.passed_tests == 1
    assert suite.failed_tests == 0


def test_testframework_captures_failures():
    fw = TestFramework()

    def bad_test():
        raise AssertionError("nope")

    fw.register(bad_test)
    suite = fw.run()
    assert suite.failed_tests == 1
    assert suite.passed_tests == 0
    assert suite.tests[0].status == "failed"
    assert "nope" in suite.tests[0].error_message


def test_testframework_mixed_results():
    fw = TestFramework()

    def ok():
        assert True

    def bad():
        raise ValueError("x")

    fw.register(ok)
    fw.register(bad)
    suite = fw.run()
    assert suite.total_tests == 2
    assert suite.passed_tests == 1
    assert suite.failed_tests == 1


def test_get_summary():
    fw = TestFramework()

    def ok():
        assert True

    fw.register(ok)
    suite = fw.run()
    summary = fw.get_summary(suite)
    assert summary["total"] == 1
    assert summary["passed"] == 1
    assert summary["pass_rate"] == 100.0


def test_get_summary_zero_tests():
    fw = TestFramework()
    suite = fw.run()
    summary = fw.get_summary(suite)
    assert summary["total"] == 0
    assert summary["pass_rate"] == 0.0


def test_mark_test_decorator():
    @mark_test
    def tagged():
        pass

    assert getattr(tagged, "_is_test", False) is True


def test_benchmark_runner():
    runner = BenchmarkRunner()

    def fast():
        pass

    result = runner.run_benchmark("fast", fast, iterations=5)
    assert result["name"] == "fast"
    assert result["iterations"] == 5
    assert result["mean_time"] >= 0
    assert result["min_time"] <= result["max_time"]
    assert result["total_time"] == pytest.approx(result["mean_time"] * 5)
    assert len(runner.results) == 1


def test_benchmark_runner_accumulates():
    runner = BenchmarkRunner()
    runner.run_benchmark("a", lambda: None, iterations=2)
    runner.run_benchmark("b", lambda: None, iterations=2)
    assert len(runner.results) == 2


# helpers for hash tests
def hashlib_sha256(s):
    import hashlib
    return hashlib.sha256(s.encode()).hexdigest()


def hashlib_md5(s):
    import hashlib
    return hashlib.md5(s.encode()).hexdigest()


def hashlib_sha1(s):
    import hashlib
    return hashlib.sha1(s.encode()).hexdigest()
