/** Re-export all icons from @sloughgpt/strui — single source of truth */
export {
  IconChat,
  IconModels,
  IconSettings,
  IconMoon,
  IconSun,
  IconMenu,
  IconActivity,
  IconX,
  IconSearch,
  IconPlus,
  IconTrash,
  IconDownload,
  IconAlert,
  IconUpload,
  IconTraining,
  IconExport,
  IconAgents,
  IconLogin,
  IconBrain,
  IconVision,
  IconClock,
  IconTokenizer,
  IconDocument,
  IconCode,
  IconChart,
  IconBookmark,
  IconSparkle,
  IconBeaker,
  IconBenchmark,
  IconMapPin,
  IconError,
  IconMic,
  IconThumbUp,
  IconGrid,
  IconLabs,
} from '@sloughgpt/strui'

import { IconX } from '@sloughgpt/strui'
/** IconClose is IconX — alias for backward compat */
export const IconClose = IconX
