#!/usr/bin/env python3
"""Emit the frontend contract registry from the backend descriptor registry.

The TypeScript half of the projection pipeline (AGENTS.md "Endpoint &
Transport Rule"): one descriptor (``ToolSpec``) -> many projections. This is the
NymVPN pattern — their Rust types are annotated with ``ts-rs`` and ``cargo test``
emits ``src/types/tauri.ts``, so a contract change that isn't regenerated is a
*compile* failure rather than a runtime surprise. This script is our equivalent
for a Python backend: it imports only the router modules that declare
descriptors (a static scan first, so it never boots the whole router set), reads
the resulting registry rows and writes
``apps/web/lib/protocol/contracts.gen.ts``.

Unlike the AST gates in ``check_contract.py`` this needs the app's dependencies:

    PYTHONPATH="$PWD:$PWD/packages/mogdb/src:$PWD/packages/downcraft:$PWD/packages/core-py:$PWD/apps/api/server" \
        python scripts/gen_ts_contracts.py           # write the file
    python scripts/gen_ts_contracts.py --check       # freshness gate (exit 1 if stale)

Freshness is enforced by ``tests/api-server/test_ts_contracts.py::test_ts_contract_projection_is_fresh``
— descriptors changed without regen => red.
"""

from __future__ import annotations

import argparse
import ast
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
ROUTERS_DIR = ROOT / "apps" / "api" / "server" / "routers"
OUTPUT = ROOT / "apps" / "web" / "lib" / "protocol" / "contracts.gen.ts"

sys.path.insert(0, str(ROOT / "apps" / "api" / "server"))

HEADER = """\
// GENERATED by scripts/gen_ts_contracts.py — do not edit by hand.
// Regenerate after changing any descriptor:
//   PYTHONPATH="$PWD:$PWD/packages/mogdb/src:$PWD/packages/downcraft:$PWD/packages/core-py:$PWD/apps/api/server" \\
//     python scripts/gen_ts_contracts.py
// Freshness gate: tests/api-server/test_ts_contracts.py::test_ts_contract_projection_is_fresh
import type { ContractDescriptor } from './types'

"""


def descriptor_modules() -> list[str]:
    """Router modules declaring a ``ToolSpec(...)`` — static scan, no imports."""
    modules: list[str] = []
    for path in sorted(ROUTERS_DIR.glob("*.py")):
        if path.name.startswith("_"):
            continue
        try:
            tree = ast.parse(path.read_text(encoding="utf-8"))
        except SyntaxError:
            continue
        for node in ast.walk(tree):
            if not isinstance(node, ast.Call):
                continue
            func = node.func
            name = func.id if isinstance(func, ast.Name) else getattr(func, "attr", "")
            if name == "ToolSpec":
                modules.append(path.stem)
                break
    return modules


def build_source() -> str:
    """Render ``contracts.gen.ts`` from the live registry rows."""
    for stem in descriptor_modules():
        __import__(f"routers.{stem}")
    from infrastructure.contract import get_contracts  # noqa: PLC0415 — after router imports

    entries = sorted(get_contracts(), key=lambda entry: entry["name"])
    rows = []
    for entry in entries:
        body = json.dumps(entry, indent=2, sort_keys=True).replace("\n", "\n  ")
        rows.append(f"  {json.dumps(entry['name'])}: {body},")
    table = "\n".join(rows)
    return (
        f"{HEADER}export const CONTRACTS = {{\n{table}\n}}"
        " as const satisfies Record<string, ContractDescriptor>\n"
        "\n"
        "export type ContractName = keyof typeof CONTRACTS\n"
    )


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if the file is stale")
    args = parser.parse_args(argv)

    expected = build_source()
    if not args.check:
        OUTPUT.parent.mkdir(parents=True, exist_ok=True)
        OUTPUT.write_text(expected, encoding="utf-8")
        print(f"wrote {OUTPUT.relative_to(ROOT)}")
        return 0

    if not OUTPUT.is_file():
        print(f"✗ {OUTPUT.relative_to(ROOT)} is missing — run scripts/gen_ts_contracts.py")
        return 1
    if OUTPUT.read_text(encoding="utf-8") != expected:
        print(
            f"✗ {OUTPUT.relative_to(ROOT)} is stale — regenerate with scripts/gen_ts_contracts.py"
        )
        return 1
    print(f"✓ {OUTPUT.relative_to(ROOT)} matches the registry")
    return 0


if __name__ == "__main__":
    sys.exit(main())
