#!/usr/bin/env python3
"""Emit the frontend contract registry from the backend descriptor registry.

The TypeScript half of the projection pipeline (AGENTS.md "Endpoint &
Transport Rule"): one descriptor (``ToolSpec``) -> many projections. This is the
NymVPN pattern — their Rust types are annotated with ``ts-rs`` and ``cargo test``
emits ``src/types/tauri.ts``, so a contract change that isn't regenerated is a
*compile* failure rather than a runtime surprise. This script is our equivalent
for a Python backend: it imports only the router modules that declare
descriptors (a static scan first, so it never boots the whole router set), reads
the resulting registry rows, and writes one artifact per consumer.

Every output is **byte-identical and self-contained**: the emitted file declares
its own ``ContractDescriptor``/``JsonSchema`` rather than importing them, so the
same bytes land in any TypeScript tree without a relative-import dependency.
That is what makes one descriptor serve several frontends — the web app, the
SDK, and the mobile app each get a copy that needs nothing else from the repo.
Mobile in particular is *not* an npm workspace member and carries its own
toolchain, yet it consumes the same bytes: the artifact imports nothing, so it
typechecks under ``apps/mobile/tsconfig.json`` with no resolution change.

Unlike the AST gates in ``check_contract.py`` this needs the app's
dependencies:

    PYTHONPATH="$PWD:$PWD/packages/mogdb/src:$PWD/packages/downcraft:$PWD/packages/core-py:$PWD/apps/api/server" \
        python scripts/gen_ts_contracts.py           # write every output
    python scripts/gen_ts_contracts.py --check       # freshness gate (exit 1 if stale)

Freshness is enforced by ``tests/api-server/test_ts_contracts.py::test_ts_contract_projection_is_fresh``
— descriptors changed without regen => red.
"""

from __future__ import annotations

import argparse
import ast
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
ROUTERS_DIR = ROOT / "apps" / "api" / "server" / "routers"

# One artifact per frontend consumer. Every entry must also be listed in
# .prettierignore: the generator owns these bytes, and lint-staged running
# prettier over them would requote the file and turn the freshness gate red.
OUTPUTS: tuple[Path, ...] = (
    ROOT / "apps" / "web" / "lib" / "protocol" / "contracts.gen.ts",
    ROOT / "packages" / "sdk-ts" / "typescript-sdk" / "src" / "contracts.gen.ts",
    # Mobile is not an npm workspace member and runs its own toolchain, but it
    # does not need to be: the artifact imports nothing, so it typechecks under
    # apps/mobile/tsconfig.json (include: src/**) with no resolution change.
    ROOT / "apps" / "mobile" / "src" / "services" / "contracts.gen.ts",
)

sys.path.insert(0, str(ROOT / "apps" / "api" / "server"))

# Self-contained by design — no `import type ... from './types'`. Portability is
# the whole point of emitting one artifact for several frontends.
HEADER = """\
// GENERATED by scripts/gen_ts_contracts.py — do not edit by hand.
// Regenerate after changing any descriptor:
//   PYTHONPATH="$PWD:$PWD/packages/mogdb/src:$PWD/packages/downcraft:$PWD/packages/core-py:$PWD/apps/api/server" \\
//     python scripts/gen_ts_contracts.py
// Freshness gate: tests/api-server/test_ts_contracts.py::test_ts_contract_projection_is_fresh

/** JSON Schema view of a capability's parameters (`ToolSpec.params` projection). */
export interface JsonSchema {
  type?: string
  properties?: Record<string, unknown>
  required?: readonly string[]
  items?: unknown
  [key: string]: unknown
}

/** One capability crossing, exactly as the backend registry declares it. */
export interface ContractDescriptor {
  name: string
  version: string
  auth_scope: string
  idempotent: boolean
  description: string
  method: string
  path: string
  operation_id: string
  module: string
  params: JsonSchema
  result: JsonSchema | null
}

"""


def descriptor_modules() -> list[str]:
    """Router modules declaring a ``ToolSpec(...)`` — static scan, no imports."""
    modules: list[str] = []
    for path in sorted(ROUTERS_DIR.glob("*.py")):
        if path.name.startswith("_"):
            continue
        try:
            tree = ast.parse(path.read_text(encoding="utf-8"))
        except SyntaxError:
            continue
        for node in ast.walk(tree):
            if not isinstance(node, ast.Call):
                continue
            func = node.func
            name = func.id if isinstance(func, ast.Name) else getattr(func, "attr", "")
            if name == "ToolSpec":
                modules.append(path.stem)
                break
    return modules


def build_source() -> str:
    """Render the artifact from the live registry rows."""
    for stem in descriptor_modules():
        __import__(f"routers.{stem}")
    from infrastructure.contract import get_contracts  # noqa: PLC0415 — after router imports

    entries = sorted(get_contracts(), key=lambda entry: entry["name"])
    rows = []
    for entry in entries:
        body = json.dumps(entry, indent=2, sort_keys=True).replace("\n", "\n  ")
        rows.append(f"  {json.dumps(entry['name'])}: {body},")
    table = "\n".join(rows)
    return (
        f"{HEADER}export const CONTRACTS = {{\n{table}\n}}"
        " as const satisfies Record<string, ContractDescriptor>\n"
        "\n"
        "export type ContractName = keyof typeof CONTRACTS\n"
    )


def rel(path: Path) -> str:
    return str(path.relative_to(ROOT))


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if any output is stale")
    args = parser.parse_args(argv)

    expected = build_source()

    if not args.check:
        for output in OUTPUTS:
            output.parent.mkdir(parents=True, exist_ok=True)
            output.write_text(expected, encoding="utf-8")
            print(f"wrote {rel(output)}")
        return 0

    stale = [o for o in OUTPUTS if not o.is_file() or o.read_text(encoding="utf-8") != expected]
    if stale:
        for output in stale:
            reason = "is missing" if not output.is_file() else "is stale"
            print(f"✗ {rel(output)} {reason} — regenerate with scripts/gen_ts_contracts.py")
        return 1
    for output in OUTPUTS:
        print(f"✓ {rel(output)} matches the registry")
    return 0


if __name__ == "__main__":
    sys.exit(main())
