#!/usr/bin/env python3
"""Generate ``apps/api/server/routers/_manifest.py`` — the boot router manifest.

Half of the boot-time self-registration design: ``get_all_routers()`` reads
``ROUTER_MODULES`` instead of a hand-edited list buried in the function, and
this script keeps that file honest. Adding a router module = dropping the file
in ``routers/`` and re-running the generator; no central switchyard edit.

Usage:
    python scripts/gen_router_manifest.py           # rewrite the manifest
    python scripts/gen_router_manifest.py --check   # CI: fail if it is stale

Rules:
    * a module belongs in the manifest only if it is public and exposes a
      module-level ``router`` (that is the boot contract ``get_all_routers()``
      looks for — class-based routers like ``api_keys`` are included by their
      owner instead);
    * modules whose ``router`` ``main.py`` imports and registers itself
      pre-lifespan (``/health`` and friends must answer during model load) are
      excluded — listing them would register every one of them twice;
    * existing order is preserved: Starlette matches routes in registration
      order, so reordering this file would silently change precedence;
    * genuinely new modules are appended alphabetically;
    * entries whose module no longer exists are dropped (reported as stale).

Stdlib only — runnable in CI with no dependencies installed.
"""

from __future__ import annotations

import argparse
import ast
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
ROUTERS_DIR = ROOT / "apps" / "api" / "server" / "routers"
MANIFEST_PATH = ROUTERS_DIR / "_manifest.py"

HEADER = '''"""Boot router manifest — GENERATED by scripts/gen_router_manifest.py.

Do not edit by hand: run ``python scripts/gen_router_manifest.py`` (and
``--check`` in CI) instead. Order is significant — Starlette matches routes in
registration order, so this list is also the route-precedence order.
"""

# fmt: off
ROUTER_MODULES: list[str] = [
'''
FOOTER = """]
# fmt: on
"""


def _has_module_router(path: Path) -> bool:
    """True if the module exposes a module-level ``router`` (the boot contract)."""
    try:
        tree = ast.parse(path.read_text(encoding="utf-8"))
    except SyntaxError:
        return False
    for node in tree.body:
        targets: list[str] = []
        if isinstance(node, ast.Assign):
            targets = [t.id for t in node.targets if isinstance(t, ast.Name)]
        elif isinstance(node, ast.AnnAssign) and isinstance(node.target, ast.Name):
            targets = [node.target.id]
        if "router" in targets:
            return True
    return False


def directly_registered(main_py: Path | None = None) -> set[str]:
    """Modules ``main.py`` imports ``router`` from and registers itself.

    Those routes go up pre-lifespan (``/health`` must answer while models
    load), so they must stay out of the manifest — listing them would register
    each of them twice. Derived from ``main.py`` rather than hardcoded so the
    two registration sites cannot drift apart silently.
    """
    main_py = main_py or (ROUTERS_DIR.parent / "main.py")
    if not main_py.is_file():
        return set()
    text = main_py.read_text(encoding="utf-8")
    return set(re.findall(r"^from routers\.(\w+) import router", text, re.MULTILINE))


def scan_modules() -> list[str]:
    """Public router modules present on disk, alphabetically."""
    if not ROUTERS_DIR.is_dir():
        return []
    excluded = directly_registered()
    return sorted(
        p.stem
        for p in ROUTERS_DIR.glob("*.py")
        if not p.name.startswith("_") and p.stem not in excluded and _has_module_router(p)
    )


def read_manifest(path: Path = MANIFEST_PATH) -> list[str] | None:
    """Parse ROUTER_MODULES out of the manifest (None if missing/unparseable)."""
    if not path.is_file():
        return None
    try:
        tree = ast.parse(path.read_text(encoding="utf-8"))
    except SyntaxError:
        return None
    for node in tree.body:
        targets: list[str] = []
        if isinstance(node, ast.Assign):
            targets = [t.id for t in node.targets if isinstance(t, ast.Name)]
        elif isinstance(node, ast.AnnAssign) and isinstance(node.target, ast.Name):
            targets = [node.target.id]
        if "ROUTER_MODULES" in targets:
            value = node.value
            if isinstance(value, (ast.List, ast.Tuple)):
                return [
                    elt.value
                    for elt in value.elts
                    if isinstance(elt, ast.Constant) and isinstance(elt.value, str)
                ]
    return None


def reconcile(current: list[str], on_disk: list[str]) -> tuple[list[str], list[str], list[str]]:
    """Merge manifest order with disk truth.

    Returns ``(result, stale, added)``: the file to write, entries whose module
    vanished, and modules never registered before.
    """
    disk = set(on_disk)
    kept = [m for m in current if m in disk]
    stale = [m for m in current if m not in disk]
    added = sorted(disk - set(kept))
    return kept + added, stale, added


def render(names: list[str]) -> str:
    body = "".join(f'    "{name}",\n' for name in names)
    return HEADER + body + FOOTER


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="do not write; exit 1 if the manifest is stale",
    )
    args = parser.parse_args(argv)

    on_disk = scan_modules()
    if not on_disk:
        print(f"error: no router modules found in {ROUTERS_DIR}", file=sys.stderr)
        return 1

    current = read_manifest() or []
    result, stale, added = reconcile(current, on_disk)
    expected = render(result)
    actual = MANIFEST_PATH.read_text(encoding="utf-8") if MANIFEST_PATH.is_file() else None

    if args.check:
        if actual == expected:
            print(f"manifest up to date ({len(result)} router modules)")
            return 0
        print("router manifest is stale:", file=sys.stderr)
        for name in stale:
            print(f"  stale entry (module gone): {name}", file=sys.stderr)
        for name in added:
            print(f"  unregistered module: {name}", file=sys.stderr)
        if not stale and not added:
            print("  manifest content differs from generated output", file=sys.stderr)
        print("run: python scripts/gen_router_manifest.py", file=sys.stderr)
        return 1

    MANIFEST_PATH.write_text(expected, encoding="utf-8")
    print(f"wrote {MANIFEST_PATH.relative_to(ROOT)}: {len(result)} router modules")
    for name in stale:
        print(f"  dropped stale entry: {name}")
    for name in added:
        print(f"  appended new module: {name}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
