"""Backward-compatibility shim — imports from the new ``domain.memory`` package."""

from domain.memory import (
    TASK_CONSOLIDATE,
    TASK_REMEMBER,
    TASK_STORE,
    KnowledgeMemoryProvider,
    MemoryConfig,
    MemoryProvider,
    MemoryService,
    archive_stats,
    get_memory_service,
    list_archive,
    maintenance_tick,
    plan_consolidation,
    prune_archive,
    register_memory_handlers,
    start_memory_maintenance,
    stop_memory_maintenance,
    submit_memory_consolidate,
    submit_memory_remember,
    submit_memory_store,
    unregister_memory_handlers,
)

__all__ = [
    "MemoryConfig",
    "MemoryProvider",
    "KnowledgeMemoryProvider",
    "MemoryService",
    "get_memory_service",
    "plan_consolidation",
    "TASK_REMEMBER",
    "TASK_STORE",
    "TASK_CONSOLIDATE",
    "register_memory_handlers",
    "unregister_memory_handlers",
    "submit_memory_remember",
    "submit_memory_store",
    "submit_memory_consolidate",
    "maintenance_tick",
    "start_memory_maintenance",
    "stop_memory_maintenance",
    "list_archive",
    "archive_stats",
    "prune_archive",
]
