"""Backward-compatibility shim — imports from the new ``domain.collections`` package."""

from domain.collections import (
    Record, Source, FileSource, UrlSource, RssSource, ApiSource,
    SseSource, WatchSource, GeneratorSource,
    Store, FileStore, MemoryStore, CallbackStore,
    ChainedStore, StatsStore,
    Filter, LengthFilter, DedupFilter, KeywordFilter, RegexFilter,
    LanguageFilter, FilterChain, SamplerFilter, TransformFilter,
    TruncateFilter, PrefixFilter, MetadataFilter,
    Collector, ParallelCollector, BatchCollector,
    Schema, DataValidator, DataEnricher, EnrichmentRule,
    RateLimiter, CallableSource, CallableStore, CollectorRunner,
    JobConfig, JobScheduler, CollectorMonitor, CollectorExporter,
    CollectorBuilder, DataSource, DataSink, DataTransformer,
    WorldFeedConfig, RecordToWorldMapper, WorldGridBridge,
    WorldGridSource, WorldStoreAdapter, CollectionWorldPipeline,
    TrainingDataConfig, TrainingDataAdapter, RecordToTrainingSource,
    TrainingDatasetBuilder, CollectorTrainingBridge,
    CollectionPipeline, CollectionRegistry, get_registry,
    SourceConfig, StoreConfig, FilterConfig, PipelineConfig,
    collect_file, collect_url, collect_rss, collect_api, collect_records,
)

__all__ = [
    "Record", "Source", "FileSource", "UrlSource", "RssSource", "ApiSource",
    "SseSource", "WatchSource", "GeneratorSource",
    "Store", "FileStore", "MemoryStore", "CallbackStore",
    "ChainedStore", "StatsStore",
    "Filter", "LengthFilter", "DedupFilter", "KeywordFilter", "RegexFilter",
    "LanguageFilter", "FilterChain", "SamplerFilter", "TransformFilter",
    "TruncateFilter", "PrefixFilter", "MetadataFilter",
    "Collector", "ParallelCollector", "BatchCollector",
    "Schema", "DataValidator", "DataEnricher", "EnrichmentRule",
    "RateLimiter", "CallableSource", "CallableStore", "CollectorRunner",
    "JobConfig", "JobScheduler", "CollectorMonitor", "CollectorExporter",
    "CollectorBuilder", "DataSource", "DataSink", "DataTransformer",
    "WorldFeedConfig", "RecordToWorldMapper", "WorldGridBridge",
    "WorldGridSource", "WorldStoreAdapter", "CollectionWorldPipeline",
    "TrainingDataConfig", "TrainingDataAdapter", "RecordToTrainingSource",
    "TrainingDatasetBuilder", "CollectorTrainingBridge",
    "CollectionPipeline", "CollectionRegistry", "get_registry",
    "SourceConfig", "StoreConfig", "FilterConfig", "PipelineConfig",
    "collect_file", "collect_url", "collect_rss", "collect_api", "collect_records",
]
