// GENERATED by scripts/gen_ts_contracts.py — do not edit by hand.
// Regenerate after changing any descriptor:
//   PYTHONPATH="$PWD:$PWD/packages/mogdb/src:$PWD/packages/downcraft:$PWD/packages/core-py:$PWD/apps/api/server" \
//     python scripts/gen_ts_contracts.py
// Freshness gate: tests/api-server/test_ts_contracts.py::test_ts_contract_projection_is_fresh
import type { ContractDescriptor } from './types'

export const CONTRACTS = {
  'contracts/list': {
    auth_scope: 'public',
    description: 'List every descriptor-projected HTTP contract registered at boot',
    idempotent: true,
    method: 'GET',
    module: 'routers.contracts',
    name: 'contracts/list',
    operation_id: 'contracts/list.get',
    params: {
      properties: {
        name: {
          description: 'Case-insensitive substring to filter descriptor names',
          type: 'string',
        },
      },
      required: [],
      type: 'object',
    },
    path: '/contracts',
    result: null,
    version: '1',
  },
} as const satisfies Record<string, ContractDescriptor>

export type ContractName = keyof typeof CONTRACTS
