// Protocol schema vocabulary — the frontend projection of the backend's
// descriptor contract (ToolSpec → RouteEntry, see docs/TRANSPORT_PROJECTIONS.md).
// Data lands in contracts.gen.ts (generated by scripts/gen_ts_contracts.py).

/** JSON Schema view of a capability's parameters (`ToolSpec.params` projection). */
export interface JsonSchema {
  type?: string
  properties?: Record<string, unknown>
  required?: readonly string[]
  items?: unknown
  [key: string]: unknown
}

/** One capability crossing, exactly as the registry declares it. */
export interface ContractDescriptor {
  name: string
  version: string
  auth_scope: string
  idempotent: boolean
  description: string
  method: string
  path: string
  operation_id: string
  module: string
  params: JsonSchema
  result: JsonSchema | null
}

export type ReadStatus = 'idle' | 'loading' | 'success' | 'error'

/** Query parameters for a capability read — coerced to strings on the wire. */
export type EndpointParams = Record<string, string | number | boolean>

/** One read's state machine slice, keyed by capability + version + params. */
export interface ReadSlice {
  status: ReadStatus
  data?: unknown
  error?: string
  /** Epoch ms of the last settled attempt (0 while idle). */
  updatedAt: number
}
